title: Tae Soo Kim
profile: /assets/img/profile_new.jpeg
description: My work falls in the intersection of human-computer interaction (HCI) and artificial intelligence (AI). I explore interaction and AI techniques that can enable users to create or adapt software tools that are tailored to their own needs and challenges. Specifically, I design interactive modules that users can compose into bespoke tools.
last_update: May 06, 2024
google_analytics: G-96HVK9168K