title: Tae Soo Kim
profile: /assets/img/profile_new.jpeg
description: I'm interested in the intersection of human-computer interaction (HCI) and artificial intelligence (AI). I design interaction techniques powered by machine learning models that enable and facilitate intent-driven creation (e.g., designing, writing).
last_update: Apr 27, 2022
google_analytics: G-96HVK9168K
