title: Tae Soo Kim
profile: /assets/img/profile_new.jpeg
description: My work falls in the intersection of human-computer interaction (HCI) and artificial intelligence (AI). I design tools that enable users to design, develop, and test novel applications powered by machine learning models. Recently, I have been interested in investigating how to embed human and personal values into ML models.
last_update: Oct 13, 2023
google_analytics: G-96HVK9168K
