title: Tae Soo Kim
profile: /assets/img/profile_new.jpeg
description: My work falls in the intersection of human-computer interaction (HCI) and artificial intelligence (AI). I explore how to disentangle natural language into interactable components that empower users to interactively control and audit AI models.
last_update: April 24, 2025
google_analytics: G-96HVK9168K