title: Tae Soo Kim
profile: /assets/img/profile_new.jpeg
description: I'm interested in intersection of human-computer interaction (HCI) and natural language processing (NLP). Specifically, I design techniques to enable users to perform tasks by expressing intentions through natural language.
last_update: Apr 20, 2022
