title: Tae Soo Kim
profile: /assets/img/profile_new.jpeg
description: My work falls in the intersection of human-computer interaction (HCI) and artificial intelligence (AI). I design interaction techniques powered by machine learning (ML) models that enable and facilitate intent-driven creation (e.g., design, writing). Recently, I have been interested in investigating how to modularize ML models or pipelines to enable users to interact with these modules to manipulate these pipelines.
last_update: Apr 16, 2023
google_analytics: G-96HVK9168K
